drop table answer if exists;

drop table question if exists;

drop table user if exists;

create table user (
    id bigint generated by default as identity,
    created_date binary(255),
    modified_date binary(255),
    email varchar(255),
    name varchar(12) not null,
    password varchar(15) not null,
    user_id varchar(12) not null,
    primary key (id)
);

create table question (
    id bigint generated by default as identity,
    created_date binary(255),
    modified_date binary(255),
    contents varchar(255),
    count_of_comment integer not null,
    title varchar(255),
    writer_id bigint,
    primary key (id)
);

create table answer (
    id bigint generated by default as identity,
    created_date binary(255),
    modified_date binary(255),
    contents varchar(255),
    question_id bigint,
    writer_id bigint,
    primary key (id)
);

alter table user 
    add constraint UK_a3imlf41l37utmxiquukk8ajc unique (user_id);

alter table answer 
    add constraint fk_question_id 
    foreign key (question_id) 
    references question;
 
alter table answer 
    add constraint fk_answer_writer 
    foreign key (writer_id) 
    references user;
 
alter table question 
    add constraint fk_question_writer 
    foreign key (writer_id) 
    references user;